metricbeat.modules:
  - module: system
    metricsets:
      - cpu
      - memory
      - network
      - filesystem
      - diskio
    enabled: true
    period: 10s

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

